services:
    bk.wh.back.base_controller:
        class: WH\BackendBundle\Controller\Backend\BaseController
        arguments: ['@service_container']
    bk.wh.back.index_controller:
        class: WH\BackendBundle\Services\Backend\IndexController
        arguments: ['@service_container']
    bk.wh.back.order_controller:
        class: WH\BackendBundle\Services\Backend\OrderController
        arguments: ['@service_container']
    bk.wh.back.create_controller:
        class: WH\BackendBundle\Services\Backend\CreateController
        arguments: ['@service_container']
    bk.wh.back.update_controller:
        class: WH\BackendBundle\Services\Backend\UpdateController
        arguments: ['@service_container']
    bk.wh.back.delete_controller:
        class: WH\BackendBundle\Services\Backend\DeleteController
        arguments: ['@service_container']
    bk.wh.back.translator:
        class: WH\BackendBundle\Services\Backend\Translator
        arguments: ['@service_container']
    bk.wh.back.srcbundleinstallator:
        class: WH\BackendBundle\Services\Backend\SrcBundleInstallator
        arguments: ['@service_container']
    bk.wh.back.form.entry:
        class: WH\BackendBundle\Form\EntryType
        arguments: ['@service_container']